name: 'Setup Flutter Project'
description: 'Setup Java, flutter, get packages and run build-runner'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '11'
    - uses: subosito/flutter-action@v2.0.3
      with:
        channel: 'stable'
    - name: Get Packages
      run: flutter pub get
    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs