on:
  workflow_call:
    inputs:
      build-args:
        required: false
        type: string
      keystore-path:
        required: false
        type: string
        default: 'app/keystore.jks'
      lane-name:
        required: false
        type: string
        default: firebase
      lane-options:
        required: false
        type: string
    secrets:
      encoded-keystore:
        required: true
      encoded-keystore-properties:
        required: true
      firebase-service-account:
        required: true

jobs:
  default:
    name: Build and Deploy to Firebase App Distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
          working-directory: android
          
      - name: Install flutter packages
        run: flutter pub get

      - name: Setup keystore
        run: |
          echo "$KEY_PROPERTIES" | base64 --decode > key.properties
          echo "$KEYSTORE" | base64 --decode > ${{ inputs.keystore-path }}
        working-directory: android
        env:
          KEYSTORE: ${{ secrets.encoded-keystore }}
          KEY_PROPERTIES: ${{ secrets.encoded-keystore-properties }}

      - run: cat 'key.properties'
        working-directory: android

      - name: Setup Firebase Service Account
        run: echo "$FIREBASE_SERVICE_ACCOUNT" > firebase_service_account.json
        working-directory: android
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.firebase-service-account }}

      - name: Build
        run: flutter build appbundle --release ${{ inputs.build-args }}
        
      - name: Upload to Firebase App Distribution
        run: bundle exec fastlane ${{ inputs.lane-name }} ${{ inputs.options }}
        working-directory: android
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase_service_account.json
