on:
  workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '17'
    - uses: subosito/flutter-action@v2.0.4
      with:
        channel: 'stable'
    - name: Cache pubspec dependencies
    - uses: actions/cache@v2
      with:
        path: |
          ${{ env.FLUTTER_HOME }}/.pub-cache
          **/.packages
          **/.flutter-plugins
          **/.flutter-plugin-dependencies
          **/.dart_tool/package_config.json
        key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          build-pubspec-
    - name: Get Packages
      run: flutter pub get
    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs
    - run: flutter analyze
