on:
  workflow_call:
    inputs:
      flutter-version:
        required: false
        type: string
        default: '3.x'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '17'
        
    - name: Install Flutter
      uses: subosito/flutter-action@v2.14.0
      with:
        flutter-version: ${{inputs.flutter-version}}
        channel: 'stable'
        cache: true
        
    - name: Load Pubspec Dependencies Cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.PUB_CACHE }}
          **/.packages
          **/.flutter-plugins
          **/.flutter-plugin-dependencies
          **/.dart_tool/package_config.json
        key: pubspec-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          pubspec-
          
    - run: flutter pub get
    - run: flutter format .
    - run: flutter pub run build_runner build
    - run: flutter analyze
