on:
  workflow_call:
    inputs:
      flutter-version:
        required: false
        type: string
        default: '2.8.1'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '17'
    - name: Load Flutter Cache
      uses: actions/cache@v2
      with:
        path: ${{ runner.tool_cache }}/flutter
        key: flutter-${{inputs.flutter-version}}
        restore-keys: |
          flutter-
    - name: Install Flutter
      uses: subosito/flutter-action@v2.0.4
      with:
        flutter-version: ${{inputs.flutter-version}}
        
    - name: Load Pubspec Dependencies Cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.PUB_CACHE }}
          **/.packages
          **/.flutter-plugins
          **/.flutter-plugin-dependencies
          **/.dart_tool/package_config.json
        key: pubspec-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          pubspec-
          
    - run: flutter pub get
    - run: flutter pub run build_runner build
    - run: flutter analyze
