name: Lint with Buf generate

on:
  workflow_call:
    inputs:
      flutter-version:
        required: false
        type: string
        default: '3.x'

      buf-user:
        required: true
        type: string

    secrets:
      buf-token:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
        
    - name: Install Flutter
      uses: subosito/flutter-action@v2.6.2
      with:
        flutter-version: ${{inputs.flutter-version}}
        channel: 'stable'
        cache: true
        
    - name: Load Pubspec Dependencies Cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.PUB_CACHE }}
          **/.packages
          **/.flutter-plugins
          **/.flutter-plugin-dependencies
          **/.dart_tool/package_config.json
        key: pubspec-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          pubspec-
          
    - run: flutter pub get
    
    - uses: bufbuild/buf-setup-action@v1.7.0
      with:
        github_token: ${{ github.token }}

    - name: Authenticate buf
      run: echo "$TOKEN" | buf registry login --username ${{ inputs.buf-user }} --token-stdin
      env:
        TOKEN: ${{ secrets.buf-token }}

    - name: Build protobuf
      run: buf generate --include-wkt --include-imports
      
    - run: flutter format .
    - run: flutter pub run build_runner build
    - run: flutter analyze
