on:
  workflow_call

jobs:
  default:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '11'
    - uses: subosito/flutter-action@v1.5.3
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter analyze