on:
  workflow_call:
    inputs:
      flutter-version:
        required: false
        type: string
        default: '2.8.1'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '17'
    - name: Cache flutter
      id: cache-flutter
      uses: actions/cache@v2
      with:
        path: ${{ runner.tool_cache }}/flutter
        key: flutter-${{inputs.flutter-version}}
        restore-keys: |
          flutter-
    - uses: subosito/flutter-action@v2.0.4
      with:
        flutter-version: ${{inputs.flutter-version}}

    - name: Cache pubspec dependencies
      id: cache-packages
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.PUB_CACHE }}
          **/.packages
          **/.flutter-plugins
          **/.flutter-plugin-dependencies
          **/.dart_tool/package_config.json
        key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          build-pubspec-
    - name: Get Packages
      run: flutter pub get

    - name: Cache build runner
      uses: actions/cache@v2
      with:
        path: |
          **/.dart_tool/build
        key: build-runner-${{ hashFiles('**/asset_graph.json') }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          build-runner-
    - name: Run build_runner
      run: flutter pub run build_runner build
      
    - run: flutter analyze
