on:
  workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Flutter Project
      uses: ./.github/actions/setup
    - run: flutter analyze
