on:
  workflow_call:
    inputs:
      entrypoint:
        required: false
        type: string
        default: 'main.dart'
      build-name:
        required: false
        type: string
        default: '0.0.1'
      build-number:
        required: false
        type: number
        default: '1'
      track:
        required: false
        type: string
        default: 'production'
      keystore-path:
        required: false
        type: string
        default: 'android/app/keystore.jks'
      keystore-properties-path:
        required: false
        type: string
        default: 'android/key.properties'
      google-play-service-account-path:
        required: false
        type: string
        default: 'android/play-store-credentials.json'
      lane-name:
        required: false
        type: string
        default: production
      lane-options:
        required: false
        type: string
      dry-run:
        required: false
        type: boolean
        default: 'false'
    secrets:
      encoded-keystore:
        required: true
      encoded-keystore-properties:
        required: true
      encoded-google-play-service-account:
        required: true

jobs:
  default:
    name: Build and Deploy to Play Store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
          working-directory: android
          
      - name: Install flutter packages
        run: flutter pub get

      - name: Setup keystore
        run: |
          echo "$KEYSTORE" | base64 --decode > ${{ inputs.keystore-path }}
          echo "$KEY_PROPERTIES" | base64 --decode > ${{ inputs.keystore-properties-path }}
        env:
          KEYSTORE: ${{ secrets.encoded-keystore }}
          KEY_PROPERTIES: ${{ secrets.encoded-keystore-properties }}

      - name: Setup play store service acoount
        run: echo "${{ secrets.encoded-google-play-service-account }}" | base64 --decode >> ${{ inputs.google-play-service-account-path }}

      - name: Get build name 
        run: echo build_name=$(echo $(git describe --tags `git rev-list --tags --max-count=1` --abbrev=0) | cut -b 2-).$(git rev-list $(git describe --tags `git rev-list --tags --max-count=1` --abbrev=0).. --count) >> $GITHUB_ENV

      - name: Get current play store version code
        run: bundle exec fastlane getVersionCode track:${{ inputs.track }}
        working-directory: android

      # - name: Build
      #   run: flutter build appbundle --release -t lib/${{ inputs.entrypoint }} --build-name=${{ inputs.build-name }} --build-number=${{ inputs.build_number }} --dart-define=${{ inputs.args }}

      - name: Build
        run: flutter build appbundle --release -t lib/${{ inputs.entrypoint }} --build-name=${{ env.build_name }} --build-number=${{ env.build_number }} --dart-define=${{ inputs.args }}
        env:
          build_number: $(( ${{env.VERSION_CODE}} + 1 ))
        
      - name: Upload to Google Play
        run: bundle exec fastlane ${{ inputs.lane-name }} dry_run:${{ inputs.dry-run }} ${{ inputs.lane-options }}
        working-directory: android
