on:
  workflow_call:
    inputs:
      build-args:
        required: false
        type: string
      keystore-path:
        required: false
        type: string
        default: 'app/keystore.jks'
      google-play-service-account-path:
        required: false
        type: string
        default: 'android/play-store-credentials.json'
      lane-name:
        required: false
        type: string
        default: production
      lane-options:
        required: false
        type: string
    secrets:
      encoded-keystore:
        required: true
      encoded-keystore-properties:
        required: true
      encoded-google-play-service-account:
        required: true

jobs:
  default:
    name: Build and Deploy to Play Store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.17.0
        with:
          channel: 'stable'

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
          working-directory: android
          
      - name: Install flutter packages
        run: flutter pub get

      - name: Setup keystore
        run: |
          echo "$KEY_PROPERTIES" | base64 --decode > key.properties
          echo "$KEYSTORE" | base64 --decode > ${{ inputs.keystore-path }}
        working-directory: android
        env:
          KEYSTORE: ${{ secrets.encoded-keystore }}
          KEY_PROPERTIES: ${{ secrets.encoded-keystore-properties }}

      - name: Setup play store service acoount
        run: echo "${{ secrets.encoded-google-play-service-account }}" | base64 --decode > ${{ inputs.google-play-service-account-path }}

      - name: Get current play store version code
        run: bundle exec fastlane getVersionCode
        working-directory: android

      - name: Build
        run: flutter build appbundle --release ${{ inputs.build-args }} --build-number=$build_number
        env:
          build_number: $(( ${{env.VERSION_CODE}} + 1 ))
        
      - name: Upload to Google Play
        run: bundle exec fastlane ${{ inputs.lane-name }} ${{ inputs.lane-options }}
        working-directory: android
